# Generated by Django 3.2.16 on 2023-06-02 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='kritik_saran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.IntegerField(choices=[(1, 'Kritik'), (2, 'Saran')])),
                ('pembahasan', models.CharField(max_length=5000)),
                ('status', models.IntegerField(choices=[(1, 'Diajukan'), (2, 'Diproses'), (3, 'Selesai')], default=1)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kritik_saran', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
