# Generated by Django 3.2.16 on 2023-05-31 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.IntegerField(choices=[(1, 'Admin'), (2, 'Petinggi Hawariyyun'), (3, 'Sekretaris'), (4, 'Bendahara'), (5, 'PSDM'), (6, 'Media Komunikasi'), (7, 'Anggota')], default=7),
        ),
    ]
