# Generated by Django 3.2.16 on 2023-06-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_profile_no_telpon'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='jurusan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='pendidikan_terakhir',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
